---
abstract: 'JSON::XS wrapper for Sledge'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom@gmail.comE<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sledge-Plugin-JSON-XS
no_index:
  directory:
    - inc
    - t
provides:
  Sledge::Plugin::JSON::XS:
    file: lib/Sledge/Plugin/JSON/XS.pm
    version: 0.04
requires:
  Filter::Util::Call: 0
  JSON::XS: 2.01
  perl: 5.00800
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
